project_id = "jxluygtonamgadqgzgyh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329

# FUNCTIONS
[functions.ai-normalize-calculate]
verify_jwt = false

[functions.ai-generate-copy]
verify_jwt = false

[functions.get-best-offer]
verify_jwt = false

[functions.scrape-offers]
verify_jwt = false

[functions.test-log]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.classify-bill]
verify_jwt = false

[functions.qa-check-offer-links]
verify_jwt = false

[functions.ai-best-offer]
verify_jwt = false